### ISSUE TITLE
SelfHosting Error : Bot Is Not Sending Any Message When Saying N Word

### ISSUE THREAD

**Issue by RaidenRafael** [Vaiterius/N-Word-Counter-Bot#8]
/===StartErrorLog==\

Traceback (most recent call last):
  File "/home/<REDACTED>/.local/lib/python3.10/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/home/<REDACTED>/DiscordSystem-Bots/N-Word_Counter-System/bot/cogs/nword_counter.py", line 175, in on_message
    if has_message_perms and guild_settings["send_message"]["value"]:
KeyError: 'send_message'

/===EndErrorLog==\

Including This Here Since It Might Help If Something Is Different From Yall Side To Mine

INFO:discord:Using Discord.py version 2.4.1
INFO:discord:Using Python version 3.10.6
INFO:discord:Running on Linux 5.15.0-76-generic (posix)

==How To Replicate==
>Just Say The N Word And The Bot Would Not Respond To The User Saying The N Word, Either Only Happens To Me Since Original Bot Is Mentioning Me When I Say The N Word

This Error Is Happening When Mentioning The N Word Every Time, I Noticed It Only Happens To Me Since Am Self Hosting It But Its A Unmodified (Just Git Cloned it), And Hosting It On My Home Linux Server (Self Hosting It Since Me And My Friends Just Spams It), Hopefully get a response from here.

**Comment by BEMZ01** [comment]
Hi @Raiden-Rafael

Make sure that you have created and activated a virtual environment (https://docs.python.org/3/library/venv.html) and have installed all the required packages with the `pip install -r requirements.txt` command from the root directory.

If you have done the above, please make sure that you have installed pycord and **not** discord.py. They both hold the same package name, but have a different install name (hence my request about installing the packages above)

**Comment by RaidenRafael** [comment]
![image](https://github.com/Vaiterius/N-Word-Counter-Bot/assets/67449286/09afd33b-5f29-4513-821c-aa9306c7de68)
![image](https://github.com/Vaiterius/N-Word-Counter-Bot/assets/67449286/4326fd23-c388-43bb-9e9c-6d8325af4a10)
Hello @BEMZ01

So I Tried Running It On A Python Enclosed VENV And The Error Still Caused On It (By The Images I Provided First)
I Dont Know If Its Herta (Home Linux) Causing It So I Give It A Shot On Windows Hosting (Didnt Have Anything installed on pip in windows since i rarely use local coding i always code via Vscode SSH) But After Trying It On Windows With Rarely Nothing Installed On Pip/python it also caused the same error

![image](https://github.com/Vaiterius/N-Word-Counter-Bot/assets/67449286/8bd027e1-b4b1-48cc-b5d9-e560414bba29)
![image](https://github.com/Vaiterius/N-Word-Counter-Bot/assets/67449286/0966a5e0-4797-4aac-80b2-1f3f29f74eda)

Either Am Doing Something Wrong Or The Code Is Conflicting To My Systems, But Either Way The Error is Still The Same On Herta Python VENV And Windows Itself, Thank you

**Comment by BEMZ01** [comment]
Hi there, sorry for the delayed response. 

Please check that you have granted the bot the message intent in the discord developer portal.

**Comment by RaidenRafael** [comment]
Hi, Also Sorry For Delayed Response

I Have already granted the message intent beforehand and it was working before, but now its not and still showing the error
![image](https://github.com/Vaiterius/N-Word-Counter-Bot/assets/67449286/9bb51b26-3848-4401-ab9b-a136dd7d2f61)

I Just Recently Have Re-installed My Server OS So It Took me A While To Respond Into This But It Still Showing The Same Issue (This Was Taken Just Now After Clarifying That Message Intent Was Granted In The DDP)
![screen](https://github.com/Vaiterius/N-Word-Counter-Bot/assets/67449286/d3d0020d-f560-4401-bff1-8d553b8adb1f)

That Image Was Taken On The Newly Installed Server With The DE So I Was Able To SS Now
